# Generated by Django 5.0.6 on 2026-01-01 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("exam", "Exam-specific"),
                            ("question", "Question-specific"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "grading_service",
                    models.CharField(
                        default="mock",
                        help_text="Grading service to use: mock, openai, claude, gemini",
                        max_length=20,
                    ),
                ),
                (
                    "service_config",
                    models.JSONField(
                        default=dict,
                        help_text="Service-specific configuration (model, temperature, etc.)",
                    ),
                ),
                (
                    "auto_grade_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Confidence threshold for auto-grading (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "require_manual_review",
                    models.BooleanField(
                        default=False,
                        help_text="Always require manual review regardless of confidence",
                    ),
                ),
                (
                    "grading_timeout",
                    models.PositiveIntegerField(
                        default=300, help_text="Grading timeout in seconds"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum retry attempts for failed grading"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="System prompt template for LLM grading"
                    ),
                ),
                (
                    "grading_prompt_template",
                    models.TextField(
                        blank=True, help_text="Grading prompt template with placeholders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_configurations",
                        to="assessments.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_configurations",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "grading configuration",
                "verbose_name_plural": "grading configurations",
                "db_table": "grading_configurations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "is_active"], name="grading_con_scope_d610ed_idx"
                    ),
                    models.Index(
                        fields=["exam", "is_active"], name="grading_con_exam_id_d3fc30_idx"
                    ),
                    models.Index(
                        fields=["question", "is_active"], name="grading_con_questio_c81887_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GradingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feedback_text", models.TextField(help_text="Detailed feedback from grading")),
                (
                    "score_breakdown",
                    models.JSONField(blank=True, help_text="Detailed score breakdown", null=True),
                ),
                (
                    "strengths",
                    models.JSONField(
                        blank=True,
                        help_text="List of strengths identified in the answer",
                        null=True,
                    ),
                ),
                (
                    "improvements",
                    models.JSONField(
                        blank=True, help_text="List of areas for improvement", null=True
                    ),
                ),
                (
                    "grading_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score of automated grading (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who provided manual feedback (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grading_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission_answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_feedback",
                        to="submissions.submissionanswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "grading feedback",
                "verbose_name_plural": "grading feedbacks",
                "db_table": "grading_feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission_answer"], name="grading_fee_submiss_5dd818_idx"
                    ),
                    models.Index(
                        fields=["grading_confidence"], name="grading_fee_grading_9c519e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GradingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grading_method",
                    models.CharField(
                        choices=[
                            ("mock", "Mock Grading"),
                            ("openai", "OpenAI GPT"),
                            ("claude", "Anthropic Claude"),
                            ("gemini", "Google Gemini"),
                            ("manual", "Manual Grading"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, help_text="Celery task ID for tracking", max_length=255
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.JSONField(blank=True, help_text="Grading result data", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if grading failed"),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_tasks",
                        to="submissions.submission",
                    ),
                ),
                (
                    "submission_answer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific answer being graded (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_tasks",
                        to="submissions.submissionanswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "grading task",
                "verbose_name_plural": "grading tasks",
                "db_table": "grading_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "status"], name="grading_tas_submiss_1ce383_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="grading_tas_status_efd74a_idx"
                    ),
                    models.Index(fields=["celery_task_id"], name="grading_tas_celery__621e8e_idx"),
                ],
            },
        ),
    ]
