# Generated by Django 5.0.6 on 2026-01-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(
                blank=True, default="", help_text="Correct answer or answer key"
            ),
        ),
    ]
