# Generated by Django 5.0.6 on 2026-01-01 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique course code (e.g., CS101)", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"role": "instructor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "db_table": "courses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Exam duration in minutes"),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "passing_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, help_text="Exam availability start time", null=True
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="Exam availability end time", null=True
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, help_text="Instructions for students"),
                ),
                (
                    "allow_review",
                    models.BooleanField(
                        default=True, help_text="Allow students to review their submissions"
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, help_text="Randomize question order for each student"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum number of attempts allowed"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="assessments.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam",
                "verbose_name_plural": "exams",
                "db_table": "exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_number", models.PositiveIntegerField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("true_false", "True/False"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of options for multiple choice questions",
                        null=True,
                    ),
                ),
                ("correct_answer", models.TextField(help_text="Correct answer or answer key")),
                (
                    "acceptable_answers",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of acceptable alternative answers",
                        null=True,
                    ),
                ),
                (
                    "use_ai_grading",
                    models.BooleanField(
                        default=False, help_text="Use AI/LLM for grading this question"
                    ),
                ),
                (
                    "grading_rubric",
                    models.TextField(
                        blank=True, help_text="Grading rubric for AI or manual grading"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, help_text="Keywords for automated grading", null=True
                    ),
                ),
                (
                    "keyword_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Weight of keyword matching in grading (0-1)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "db_table": "questions",
                "ordering": ["exam", "question_number"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["code"], name="courses_code_fa42f1_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["instructor", "is_active"], name="courses_instruc_43dca9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["course", "status"], name="exams_course__149a1a_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["status", "start_time", "end_time"], name="exams_status_42658f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["-created_at"], name="exams_created_2092f0_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam", "question_number"], name="questions_exam_id_5c273f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["question_type"], name="questions_questio_8af709_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("exam", "question_number")},
        ),
    ]
