# Generated by Django 5.0.6 on 2026-01-01 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(default=False, help_text="Whether submission was late"),
                ),
                (
                    "flagged_for_review",
                    models.BooleanField(default=False, help_text="Flag for manual review"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address from which submission was made", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="Browser user agent string")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assessments.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "submission",
                "verbose_name_plural": "submissions",
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer_text", models.TextField(help_text="Student's answer")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score awarded for this answer",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("feedback", models.TextField(blank=True, help_text="Feedback from grading")),
                (
                    "graded_by",
                    models.CharField(
                        blank=True, help_text="Grading method: auto, ai, manual", max_length=50
                    ),
                ),
                (
                    "grading_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional grading information (confidence, keywords matched, etc.)",
                        null=True,
                    ),
                ),
                (
                    "requires_manual_review",
                    models.BooleanField(default=False, help_text="Flag answer for manual review"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="assessments.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission answer",
                "verbose_name_plural": "submission answers",
                "db_table": "submission_answers",
                "ordering": ["submission", "question__question_number"],
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["student", "exam"], name="submissions_student_98b79b_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["exam", "status"], name="submissions_exam_id_770894_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["status", "-created_at"], name="submissions_status_51c352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student", "-created_at"], name="submissions_student_ee2276_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("student", "exam", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["submission", "question"], name="submission__submiss_1fe31c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(fields=["score"], name="submission__score_42bb7f_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["requires_manual_review"], name="submission__require_6cf981_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissionanswer",
            unique_together={("submission", "question")},
        ),
    ]
